export enum Resources {
  ORGANIZATIONS = 'ORGS',
  AFFILIATIONS = 'AFFILIATIONS',
  PROJECTS = 'PROJECTS',
  MEMBERS = 'MEMBERS',
  TASKS = 'TASKS',
  COMMENTS = 'COMMENTS',
  EVENTS = 'EVENTS',
  PROJECT_STATS = 'PROJECT_STATS'
}
